### PR TITLE
React 16

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR adds React 16 compatibility

#### How to test this pull request:
remove old ```node_modules```
run ```npm test```
Use component in main app and ensure usual functionality

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/translationhelps/49)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[package.json, line 46 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationhelps/49#-L2zGzjIuVn_0QOpGzc-:-L2zGzjIuVn_0QOpGzc0:b-3tr9ko) ([raw file](https://github.com/translationcoreapps/translationhelps/blob/fd773170319061f5b8ced161a03383680c4efbd8/package.json#L46)):*
> ```JSON
>     "eslint": "^4.13.1",
>     "eslint-plugin-react": "^7.5.1",
>     "fs-extra": "3.0.1",
> ```

Do we want to use the latest version of `fs-extra`?

---

*[package.json, line 48 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationhelps/49#-L2zIkvnjAu3O4kM6Jbm:-L2zIkvnjAu3O4kM6Jbn:blzli6c) ([raw file](https://github.com/translationcoreapps/translationhelps/blob/fd773170319061f5b8ced161a03383680c4efbd8/package.json#L48)):*
> ```JSON
>     "fs-extra": "3.0.1",
>     "jest": "^21.1.0",
>     "material-ui": "0.17.4",
> ```

there seems to be a few libraries here that we dont need for this tool/su

---

*[__tests__/AddSomeTests.test.js, line 2 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationhelps/49#-L2zOf_DaSrABlyCa6TI:-L2zOf_DaSrABlyCa6TJ:b-5pdkc) ([raw file](https://github.com/translationcoreapps/translationhelps/blob/fd773170319061f5b8ced161a03383680c4efbd8/__tests__/AddSomeTests.test.js#L2)):*
> ```JavaScript
> test('We have tests', () => {
>     expect(true).toBeTruthy();
> ```

I believe this test was left failing intentionally.

---

*[testSetUp/shim.js, line 1 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationhelps/49#-L2zPNL4Y9dwImW3GYFo:-L2zPNL5R-FnRNakv0i2:brmwqq9) ([raw file](https://github.com/translationcoreapps/translationhelps/blob/fd773170319061f5b8ced161a03383680c4efbd8/testSetUp/shim.js#L1)):*
> ```JavaScript
> global.requestAnimationFrame = (callback) => {
> ```

why do we need shim.js?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationhelps/49)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationhelps/49)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[package.json, line 46 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationhelps/49#-L2zGzjIuVn_0QOpGzc-:-L3UOItVpORb-LAe05F2:b-t158lp) ([raw file](https://github.com/translationcoreapps/translationhelps/blob/fd773170319061f5b8ced161a03383680c4efbd8/package.json#L46)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Do we want to use the latest version of `fs-extra`?
</blockquote></details>

Fixed to latest.

---

*[package.json, line 48 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationhelps/49#-L2zIkvnjAu3O4kM6Jbm:-L3UOKbEH1fUsP6n8aXX:bnb010b) ([raw file](https://github.com/translationcoreapps/translationhelps/blob/fd773170319061f5b8ced161a03383680c4efbd8/package.json#L48)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

there seems to be a few libraries here that we dont need for this tool/su
</blockquote></details>

Removed unneeded.

---

*[__tests__/AddSomeTests.test.js, line 2 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationhelps/49#-L2zOf_DaSrABlyCa6TI:-L3UONXMssNHow7E-taL:b-kt4n90) ([raw file](https://github.com/translationcoreapps/translationhelps/blob/fd773170319061f5b8ced161a03383680c4efbd8/__tests__/AddSomeTests.test.js#L2)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I believe this test was left failing intentionally.
</blockquote></details>

Ok, @klappy can you confirm?

---

*[testSetUp/shim.js, line 1 at r1](https://reviewable.io:443/reviews/translationcoreapps/translationhelps/49#-L2zPNL4Y9dwImW3GYFo:-L3UOQrvG2O1eBMZ2GSw:b-lr6lxg) ([raw file](https://github.com/translationcoreapps/translationhelps/blob/fd773170319061f5b8ced161a03383680c4efbd8/testSetUp/shim.js#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why do we need shim.js?
</blockquote></details>

To make react work with material-ui

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationhelps/49)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 1 of 1 files at r3, 1 of 2 files at r4.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationhelps/49#-:-L3Y5ZxyXMn8Op-1xqeV:bnfp4nl)*

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/translationhelps/49)*

**Pull request merged**
